global:
  defaultNamespace: default
  registry: azurecr.io
  replicas: 1
  security:
    defaultFsGroup: 1999
    defaultUser: 1999
    defaultGroup: 1999
    runAsNonRoot: true
  # istio:
  #   tls:
  #     credentialName: wildcard.dev.dt.local
  env:
    name: Dev
    short: dev
    imagePrefix: dev
    chartBuildId: 0
    host: ".dev.dt.local"
    isPrimary: true
  services:
    config:
      name: config
      namespace: "dev-data"
      buildId: 3.0.1007
    config_ns:
      name: config-ns
      namespace: "dev-data"
      buildId: 3.0.999
      imagePrefix: ksa-dev
      repository: config
