---
apiVersion: v1
data:
  .dockerconfigjson: 
kind: Secret
metadata:
  name: regcred
  namespace: dev-core
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: 
kind: Secret
metadata:
  name: regcred
  namespace: dev-frontend
type: kubernetes.io/dockerconfigjson
